= Graph(5)
g.add_edge(0, 1, 2)
g.add_edge(0, 3, 6)
g.add_edge(1, 2, 3)
g.add_edge(1, 3, 8)
g.add_edge(1, 4, 5)
g.add_edge(2, 4, 7)
g.add_edge(3, 4, 9)
print("Prim's MST:", g.prim())
print("Kruskal's MST:", g.kruskal())
dist, pred = g.dijkstra(0)
print("Dijkstra distances:", dist)
print("Dijkstra path to 4:", g.get_path(pred, 4))
dist, pred = g.bellman_ford(0)
print("Bellman-Ford distances:", dist)
print("Bellman-Ford path to 4:", g.get_path(pred, 4))